### ISSUE TITLE
[Bug]: [Remove GNS] NFT issues in send flow

### ISSUE THREAD

**Issue by Unik0rnMaggie** [MetaMask/metamask-mobile#18180]
### Describe the bug

The following issues are present for NFTS in the send flow

1. NFTs corresponding to Ethereum Mainnet are displayed for all networks in the send flow and sending them is possible on any network
2. NFTs corresponding to Linea network are not displayed in the send flow in the asset list, so they cannot be sent.

### Screenshots/Recordings

https://github.com/user-attachments/assets/6e1845b8-540d-4132-b806-592a4fa81916

https://github.com/user-attachments/assets/ec616a04-67f1-4bf8-b679-9285a7c72727

### Steps to reproduce

1. Have NFTs on Ethereum Mainnet or Linea
2. Click send
3. Select Linea 
4. Click on assets
5. Notice the NFTs are not displayed
6. Notice Ethereum NFTs are displayed on all networks selected in the send flow

### Error messages or log output

```shell

```

### Detection stage

On a feature branch

### Version

7.54.0

### Build type

None

### Device

iPhone 15, Pixel 6 Pro

### Operating system

iOS, Android

**Comment by darkwing** [comment]
The issue here is likely the selector for NFTs in the Send flow is always referring to the global network, which is why Ethereum NFTs always display but Linea doesn't, even when selected in the dropdown.  We either need to (1) switch global network when the contextual dropdown is selected or  (2) need the selector to only return NFTs for the contextually selected network.

**Comment by NidhiKJha** [comment]
Thanks @darkwing I think we should go with `switch global network when the contextual dropdown is selected` approach since that's also the behaviour on extension

**Comment by Prithpal-Sooriya** [comment]
NFT support is not yet added on the new send flow, but I believe this should be resolved as the new send flow does not use GNS/network filter

**Comment by NidhiKJha** [comment]
Not implemented yet

https://github.com/user-attachments/assets/ddf2615f-be88-4c58-9f24-254c640ebec3

**Comment by vinnyhoward** [comment]
> 1. NFTs corresponding to Ethereum Mainnet are displayed for all networks in the send flow and sending them is possible on any network

This is fixed with this PR [chore(runway): cherry-pick fix: cp-7.54.0 revert contextual chain id prs #18839](https://github.com/MetaMask/metamask-mobile/pull/18839)

> 2. NFTs corresponding to Linea network are not displayed in the send flow in the asset list, so they cannot be sent.

I do not have NFTs on Linea so I'm unable to validate this is fixed

**Comment by hesterbruikman** [comment]
Removing sev1 labels as this affects the legacy send flow which is only maintained as fall back.

Issue persists on Linea and exists on prod, not related to remove GNS.

Needs confirmation about whether issues persists in Send redesign

**Comment by bschorchit** [comment]
@hesterbruikman this is not an issue on the new send flow.

**Comment by bschorchit** [comment]
Closing as the new send flow has already been rolled out to users
