### ISSUE TITLE
Cannot send more than 999 tokens

### ISSUE THREAD

**Issue by tristos60** [MetaMask/metamask-mobile#1886]
**Describe the bug**
Cannot send more than 999 tokens to any public address on Metamask for Android

**Screenshots**
![Screenshot_20201009_075656_io metamask](https://user-images.githubusercontent.com/72608180/95579804-8d4bd100-0a36-11eb-80d5-f7a59241ad45.jpg)

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to your wallet
2. Press your token (BID in my example)
3. Press Send
4. Enter a public address
5. Press Next
6. Enter an amount of 1000 tokens or more
7. Press Next
8. The confirm page is loading forever and you cannot send the tokens

**Expected behavior**
Possibility to adjust the network fee and send the tokens is expected. If you try to send 999 tokens or less there is no issue.

**Smartphone (please complete the following information):**
 - Device: Huawei P30 Pro
 - OS: Android 10
 - App Version 1.0.3(37)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by EtDu** [comment]
Hey @tristos60, thank you for the report. This issue has been fixed and will be included in an upcoming release.

**Comment by tristos60** [comment]
> 
> 
> Hey @tristos60, thank you for the report. This issue has been fixed and will be included in an upcoming release.

Thank you EtDu. I have updated the app to v1.0.4(38) but the issue is still there.

**Comment by EtDu** [comment]
@tristos60 It's not a a part of that release, will likely be included in 1.0.5.
