### ISSUE TITLE
[Bug]: Unknown asset in transaction confirmation if the sending network is different than the current network

### ISSUE THREAD

**Issue by Unik0rnMaggie** [MetaMask/metamask-mobile#19151]
### Describe the bug

If the sending network if different than the one selected network in the network manager,  then the confirmation displays `Unknown` for any asset

If All popular networks is selected in the Network Manager, then the issue does not happen

If a Custom network is selected in the Network Manager, then the issue is the same

### Expected behavior

Display correct asset name instead of `Unknown` in the send transaction confirmation

### Screenshots/Recordings

![Image](https://github.com/user-attachments/assets/cd10c8d3-3703-4321-85d5-b55061d060ae)

https://github.com/user-attachments/assets/2fdcc889-26c1-486f-abad-d2151a327b50

https://github.com/user-attachments/assets/b1e9891c-198b-4289-90fb-74c8ccabb26a

### Steps to reproduce

1. Select Ethereum Mainnet from Network Manager
2. Start Send flow
3. Select a token from Linea network or any network except Ethereum Mainnet
4. Notice _Unknown_ instead of asset name in the Review Confirmation screen

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.55.0

### Build type

None

### Device

iphone 15, Pixel 6 Pro

### Operating system

iOS, Android

**Comment by jpuri** [comment]
Re-opening as cherry-pick PR is not merged

**Comment by bschorchit** [comment]
Closing as the fix was merged to main and it's only pending the cherry pick

**Comment by Unik0rnMaggie** [comment]
Issue still present in latest build 7.55.0 (**2386**):

Re-opening issue.

Steps to reproduce:

1. Send transaction on Linea
2. Switch network manager to Base Mainnet
3. Send transaction on Arbitrum

https://github.com/user-attachments/assets/9ba4cf1e-38b3-4f65-9f1a-e1dd7cc362df

![Image](https://github.com/user-attachments/assets/c9729e69-c7ed-45ee-9529-d5a3d8b18b1d)

**Comment by Unik0rnMaggie** [comment]
Unable to reproduce for native tokens. Reproduced for ERC20 tokens only:

https://github.com/user-attachments/assets/38bb955a-db97-4ef5-9bcf-20569a9fea8d
