### ISSUE TITLE
Can not add auto/manually a network to MetaMask for iPhone

### ISSUE THREAD

**Issue by aliveli186** [MetaMask/metamask-mobile#3645]
MetaMask mobile doesn't support "wallet_addEthereumChain" method. 
If you try to add the network manually it doesn't add the network either and there is no feedback of why it didn't add it, no error message.
The chain id I'm trying to add is: `31337` if it makes a difference.

**Comment by ulyanas** [comment]
Issue still reproduces

**Comment by gantunesr** [comment]
Fixed in #3685

**Comment by aliveli186** [comment]
@gantunesr Partially fixed, works on Android but still doesn't work on iPhone.

**Comment by aliveli186** [comment]
Why a simple issue can not be fixed in months?

**Comment by mortezashojaei** [comment]
same here!
any temporary solution?

**Comment by SpasiboKojima** [comment]
Still doesn't seem to work in 5.7.0.

**Comment by 0ximDean** [comment]
Still doesn't seem to work in 5.12.1 for android
