### ISSUE TITLE
wallet_watchAsset not working on mobile but works at browser extension

### ISSUE THREAD

**Issue by larry82** [MetaMask/metamask-mobile#3722]
**Describe the bug**
wallet_watchAsset not working on mobile but works at chrome-extension
here is the code

```
try {
            // wasAdded is a boolean. Like any RPC method, an error may be thrown.
            const wasAdded = await window.ethereum.request({
              method: 'wallet_watchAsset',
              params: {
                type: 'ERC20', // Initially only supports ERC20, but eventually more!
                options: {
                  address: tokenAddress, // The address that the token is at.
                  symbol: tokenSymbol, // A ticker symbol or shorthand, up to 5 chars.
                  decimals: tokenDecimals, // The number of decimals in the token
                  image: tokenImage, // A string url of the token logo
                },
              },
            });
```

**Screenshots**
I print out the value of "wasAdded" object

![photo_2022-02-09_19-58-59](https://user-images.githubusercontent.com/15089799/153196881-1626774c-8301-493a-b8e8-fb9b5f603134.jpg)
![IMG_3176](https://user-images.githubusercontent.com/15089799/153197015-951e27b3-8ecc-457e-ae34-f5e1014cf358.PNG)

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to 'https://flyingclub.io/switch_to_poly'
2. Click on '加入 Polygon 網路' to add polygon mainnet
3. Click on '加入 NZ 點數到 metamask' to add NZ ERC20 token on polygon

**Expected behavior**
everything works fine on browser extension

**Smartphone (please complete the following information):**
 - Device: ip12pro
 - OS: ios 15.1.1
 - App Version [e.g. 1.0.0]  v4.0.1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by anxiubin** [comment]
That is a bug for now. Maybe the issue will be fixed soon,  I guess.
Look at link below.

https://github.com/MetaMask/metamask-mobile/issues/3376
https://github.com/MetaMask/metamask-mobile/issues/3376

**Comment by gantunesr** [comment]
Fix in PR #3685

**Comment by gabkov** [comment]
> Fix in PR #3685

For me still not working on android in the MM app.

**Comment by gabkov** [comment]
> Fix in PR #3685

It works,but the image is not loaded on mobile. Android MM app.

**Comment by larry82** [comment]
Still not working on IOS mobile app (already update to latest version)

**Comment by larry82** [comment]
return the same error on mobile app
{"_U":0,"_V":0,"_W":null,"_X":null}

and works fine on Website

**Comment by gantunesr** [comment]
Hey @larry82, this should be fixed in the release (v4.2.2)

**Comment by jcamilli** [comment]
Hi @gantunesr, this is not fully fixed yet. Did you test on IOS? Verions 4.2.2 imports the token but not the token's picture on iOS.

**Comment by gantunesr** [comment]
Hey @jcamilli, we're taking a look on why the images are missing, I'll be posting an update here in the following days

**Comment by Amirjab21** [comment]
@gantunesr Is this now patched? Do I need to update my metamask app for it to work?

**Comment by gantunesr** [comment]
Hey @Amirjab21, this fix will be included in the next release (v5.1.0). Thank you for your patience.

**Comment by Ardziv** [comment]
This bug is still existing in latest MetaMask on iOS . Can you reopen it and fix it for good please on iOS plateform?

**Comment by Ardziv** [comment]
It works on iOS device when I change to PNG format for the token  image - however the image in PNG is very poor quality - is there a way to support SVG on MetaMask for iOS?![image](https://user-images.githubusercontent.com/13898818/212806180-2eed38bd-1f47-4ed0-96f1-d785e465e16e.jpeg)
