### ISSUE TITLE
WalletConnect - MetaMask redirects to the App Store before transaction can be authorised 

### ISSUE THREAD

**Issue by davidm03** [MetaMask/metamask-mobile#3914]
**Describe the bug**
When a user attempts to send a transaction from our dapp using WalletConnect and MetaMask - the MetaMask app will open, the transaction pop-up will appear with all the transaction details pre-filled from our dapp for a very brief period of time (maybe less than 1 second), then the MetaMask app will redirect/open the app store as if the user does not have MetaMask installed. If the user navigates back to the MetaMask app from the app store, the browser tab is open with the metamask.app.link url inserted but the user is not able to get the transaction pop-up to reappear and no response is sent back to our dapp ever. 

**To Reproduce**
Difficult to reproduce without access to our dapp but I'll do my best to explain. 

1. From a React Native dapp which uses WalletConnect - connect to your MetaMask wallet via WalletConnect pop-up window. 
2. Once MetaMask wallet is successfully connected and you have been redirected back to your dapp - attempt to call the WalletConnect sendTransaction function (code will be included below) using the same data. 
3. MetaMask mobile app is re-opened, transaction pop-up is displayed briefly before the app will redirect the user to the app store - as if they did not ever have it installed. 

The following code is being used to call the sendTransaction function via WalletConnect after a user has connected a MetaMask wallet. 

```
const sendTransaction = async (): Promise<void> => {
    await connector
      .sendTransaction({
        from: connector.accounts[0],
        to: "0xb81c36B5BCdDB20BFECE8F355DC5B212565AF907",
        value: Web3.utils.toHex(0.01 * 1e18),
        type: "native",
      })
      .then((res) => {
        console.log("Transaction Hash => ", res);
      })
      .catch((e) => console.warn(e));
  };
```

**Expected behavior**
User is redirected to MetaMask to authorise the transaction, transaction pop-up is displayed to the user for authentication, app store should not open as the user already has the app installed, user is able to approve/reject the transaction and should the be redirected back to our dapp and response returned to WalletConnect sendTransaction function. 

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: iOS 15.4
 - App Version v4.2.2 (834)

**Comment by davidm03** [comment]
Update: 
The issue is only happening on iOS devices and appears to be caused by line 136 within the WalletConnectProvider.js file

```
const url = formatWalletServiceUrl(walletService);
return (await Linking.canOpenURL(url)) && Linking.openURL(url);
```

Linking.openURL(url) launches MetaMask via the metamask.app.link URL and triggers the in-app browser, which is then redirecting the user to the app store - even if they have the app installed. 

We've came up with a workaround for this issue and deployed a patch to use the connected wallet deeplink to launch the wallet app instead of the wallet service URL previously being generated. 

```
const url = formatWalletServiceUrl(walletService);
return (await Linking.canOpenURL(url)) && Linking.openURL(walletService.mobile.native);
```

This resolves the issue for now, MetaMask opens correctly without redirected to the app store and the transaction pop-up is displayed correctly.

**Comment by epshtielsl** [comment]
The universal URL should still open MetaMask without prompting the AppStore.  Perhaps there is an issue with how they have configured the universal URL when opened with parameters (i.e. sending the sign personal message command via deep link).

**Comment by andreahaku** [comment]
Thanks @davidm03 and @epshtielsl. I'll test the fix and eventually integrate in the app. Thanks again.

**Comment by rafaelaugustos** [comment]
Any news about this problem?

**Comment by joharzmn** [comment]
@davidm03 The fix you mentioned above, How can we use that fix when using walletconnect?? I can't find `WalletConnectProvider.js` in walletConnect.

**Comment by andreahaku** [comment]
Did you try the latest version of the app (5.0.x) as most of the deep links related issue should be solved with it. Please let me know. Thanks!

**Comment by fablanglet** [comment]
I still have the issue on iOS. Metamask deep link doesn't work. It still going to App Store.

**Comment by andreahaku** [comment]
> I still have the issue on iOS. Metamask deep link doesn't work. It still going to App Store.

Did you check the solution suggested here?
https://github.com/MetaMask/metamask-mobile/issues/3965#issuecomment-1110690454

**Comment by davidm03** [comment]
> @davidm03 The fix you mentioned above, How can we use that fix when using walletconnect?? I can't find `WalletConnectProvider.js` in walletConnect.

The file I mentioned can be found within node_modules > @walletconnect > react-native-dapp > providers > WalletConnectProvider.js

We used the [patch package](https://www.npmjs.com/package/patch-package) library to create a patch to apply this fix on every npm install and ensure it's not overridden.

**Comment by y0unghe** [comment]
> I still have the issue on iOS. Metamask deep link doesn't work. It still going to App Store.

The same.

**Comment by anxolin** [comment]
@andreahaku i'm using 5.0.1 and still have the same issue in IOS Safari. 

You can try it here https://cowswap.staging.gnosisdev.com (approving a token for example).

I use `web3-react` which delegates to `@walletconnect/ethereum-provider` . Any hint on how to debug/solve the issue?
We are not the ones creating the deep links, I assume Wallet Connect is.

**Comment by rafaelaugustos** [comment]
I have same problem in my React Native app, but it is not happen in all apps

**Comment by fopina** [comment]
Not sure if related but https://metamask.app.link/dapp/Google.com from iOS safari opens App Store while clicking the same link in any “inapp browser” (like Telegram or WhatsApp) does work

**Comment by antinomy-studio** [comment]
Having the same issue on iOS. Wallet Connect opens the App Store even if MetaMask is installed + Wallet is setup.

**Comment by xaun** [comment]
The solution for me was to ensure the web3 provider send request (RPC API) was the first network request after a user action. 

I've deployed an example [here](https://web3-react-git-ios-app-store-redirect-issue-xaun.vercel.app) forked from [web3-react/example-next](https://github.com/NoahZinsmeister/web3-react/tree/main/packages/example-next ) (v8) which consistently reproduces the issue when the checkbox is ticked on iOS by making a random async request first instead. Example diff here: https://github.com/xaun/web3-react/commit/694f7913ecc77191ff410c077881cd70e7b0f50e

I'm guessing this is something to do with mobile devices blocking redirections (deeplinks/universal links/or what not) that are not detected as derived from a user action.. something along the lines maybe? I'de love to know exactly why this behaviour occurs, as it's been a bit of a journey to figure out this "gotcha".

@davidm03 what invokes your `sendTransaction` method? Is there any async behaviour before it?

**Comment by arnold-almeida** [comment]
Another point to the solution is that there were no render cycles invoked on the action

**Comment by LifeWithArt1** [comment]
Still happening for me...so frustrating.

**Comment by grp06** [comment]
Still an issue for me. I'm using Rainbow kit. 

It also happens when you use Uniswap or AAVE and try to sign in with WalletConnect. Crazy it's still broken!

**Comment by xaun** [comment]
Also don't updated your Metamask on iOS to the latest version that was released recently or it'll completely stop working. The code example I gave above doesn't work anymore, nor does connecting with well known sites like [Uniswap](https://app.uniswap.org/) (noting they're using the same underlying `web3-react` lib).

**Comment by niraj-khatiwada** [comment]
> The solution for me was to ensure the web3 provider send request (RPC API) was the first network request after a user action.
> 
> I've deployed an example [here](https://web3-react-git-ios-app-store-redirect-issue-xaun.vercel.app) forked from [web3-react/example-next](https://github.com/NoahZinsmeister/web3-react/tree/main/packages/example-next) (v8) which consistently reproduces the issue when the checkbox is ticked on iOS by making a random async request first instead. Example diff here: [xaun/web3-react@694f791](https://github.com/xaun/web3-react/commit/694f7913ecc77191ff410c077881cd70e7b0f50e)
> 
> I'm guessing this is something to do with mobile devices blocking redirections (deeplinks/universal links/or what not) that are not detected as derived from a user action.. something along the lines maybe? I'de love to know exactly why this behaviour occurs, as it's been a bit of a journey to figure out this "gotcha".
> 
> @davidm03 what invokes your `sendTransaction` method? Is there any async behaviour before it?

For some reason this works for me for both spawnBug set or unset. But my app still redirects to appstore even when spawnBug is false. Any idea?

**Comment by Tdweller** [comment]
This has frustrated me forever, but today I stumbled on a weird fix. I have no idea why it works, but it has for me every time.

When I initiate a transaction and am told to sign in my wallet, Im then automaticallyredirected to the App Store, to the MetaMask Page.

In the App Store, next to the MetaMask logo is a back arrow. (Not the one to go back to MetaMask, the one to go back to App Store home page) Tap dat.

Then, use the top right arrow to go back to MetaMask: for me, the place to sign is right there waiting.

Hope this works for others, I have no idea how or why it does for me.

**Comment by codeforreal1** [comment]
> This has frustrated me forever, but today I stumbled on a weird fix. I have no idea why it works, but it has for me every time.
> 
> 
> 
> When I initiate a transaction and am told to sign in my wallet, Im then automatically redirected to the App Store, to the MetaMask Page.
> 
> 
> 
> In the App Store, next to the MetaMask logo is a back arrow. (Not the one to go back to MetaMask, the one to go back to App Store home page) Tap dat.
> 
> 
> 
> Then, use the top left arrow to go back to MetaMask: for me, the place to sign is right there waiting.
> 
> 
> 
> Hope this works for others, I have no idea how or why it does for me.

If the metamask is not in quit state, the transaction is already pending in metamask. Its just the redirection was gone to Appstore.

**Comment by sra-fiberswitch** [comment]
I had the same issue on my iPhone. Fixed it by long-pressing the MetaMask symbol when in the WalletConnect menu. You get a dropdown list whereafter you can select “Open with MetaMask”.

**Comment by JstKuLam** [comment]
Having the same issue on iOS. The latest Metamask version. Wallet Connect opens the App Store even if MetaMask is installed. So frustrating

p/s: Other wallets worked fine (Coin98, Trust, GNosis...)

**Comment by SunnyCheung-cp** [comment]
Unfortunately, I also ran into this problem. Is there a solution now?

**Comment by andreahaku** [comment]
We just release an update of the app (v5.12.0 and up) that should help fix this issue. It's rolling out now on Android and iOS. Please let me know if this solves or not. Thanks

**Comment by andreahaku** [comment]
@SunnyCheung-cp we don't support WC v2.0 for now. We only support WC v1

**Comment by ZiggStardust** [comment]
@andreahaku why won't you support WC v2 ? What is the reason behind this ? Metamask has a large market share of wallets out there and wallet connect provides a great UX experience for onboarding users....

**Comment by GainsGoblin** [comment]
Bruh fix this already

**Comment by markoorn** [comment]
How is this still ongoing after a full year? Is there any working for browser apps similar to what @davidm03 did for the native dependency? I have a web app which is largely used on phones and am struggling to get a decent UX with walletconnect and MetaMask

**Comment by hinahoh0** [comment]
it's like this issue comes up again after every upgrade. can't it be fixed once and for all?

**Comment by andreahaku** [comment]
This has been tackled multiple times already but some still have this problem. What we've found for example is that this mainly happens on iOS. This may happen if you have a not "stable" (read beta or RC) version of iOS installed on your iOS device.

WC is aware of that and to finally fix this they are developing a new modal that uses deep links (so URL schemas like `metamask://` and `wc://`) instead of Universal Links (`https://metamask.app.link/`) and we already have a PR (https://github.com/MetaMask/metamask-mobile/pull/6076) that should be out soon supporting this change.

Hopefully this should solve the unreliability of some WC connections using universal links.

**Comment by anxolin** [comment]
I agree, this is super annoying, we get complaints from time to time. I also experienced it many times, and I don't have a `non stable IOS` version

Awesome if this PR fixes it, it has been there for a while and I feel like especially WC is important for mobile devices, and IOS is nothing to leave behind. 

Thanks in advance to the one tackling it, I hope the new solution works 🤞

**Comment by derrick-ag** [comment]
This issue happens(for me) after I was asked to redirect (open) MetaMask to sign a transaction and I clicked on cancel (because it was a mistake).. there after I got redirected to the AppStore and not the app. Same with other wallets.

**Comment by aktoriukas** [comment]
Is there any solution for this??
my issue is that - while trying to connect the wallet to the site it directs to the app store instead of the application.

the weird part about it is that on some phones ( IOS ) it does it correctly and on others, it does not.

**Comment by arbaz-meo** [comment]
i m also facing one issue its exist on triggering the transaction not on connection  when i connect wallet and use ### https://metamask.app.link/wc?uri=ecncode(wc)  so its open wallet and pop up appear then redirect to the dapp .  
now when i trgger the transaction i use ### https://metamask.app.link its take me to the wallet pop up appear for transaction but its not redirect me to the wallet

**Comment by HarlamovEvgeniy** [comment]
This problem is still relevant, we are waiting for fixes.

**Comment by christopherferreira9** [comment]
Hi all! We are trying to replicate this issue.

**Comment by 22JH** [comment]
The problem is still not resolved.
