### ISSUE TITLE
Android 12 Chainsafe Signing Request Deep Link Not Working

### ISSUE THREAD

**Issue by brian-kryptomon** [MetaMask/metamask-mobile#3923]
**Describe the bug**
On Android 12 running Metamask 4.2.2, we initiate a signing request from our Android app that uses this link:

https://metamask.app.link/dapp/chainsafe.github.io/game-web3wallet/?action=sign&message=1647728295

The browser asks what app we want to use for the activity and we click Metamask which opens the app but then there is no prompt for a signing.  

We perform this same action on Android 11 on Metamask 4.2.2 and we are prompted for signing correctly and the app works as expected.

This is currently a major concern as we go to rollout our mobile game as most of our users are using Metamask.

**Screenshots**

**To Reproduce**
Create a signing request using Chainsafe
Browser redirects to Metamask but no signing request is shown and it just sits there.

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - Device: Samsung S8 Tablet
 - OS: Android 12
 - App Version [e.g. 1.0.0] - 4.2.2

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by cortisiko** [comment]
@brian-kryptomon This was fixed in v4.3.1. Can you confirm this on your end?

**Comment by brian-kryptomon** [comment]
@cortisiko I just downloaded 4.3.1 and tested and it still doesn’t prompt for signing. I also asked the Chainsafe team and they tested the latest version as well and they confirmed it wasn’t fixed either.

**Comment by brian-kryptomon** [comment]
So I updated my MetaMask install via the play store and it wasn’t working but one of my engineers downloaded it from github via APK and it works. The version shows the same on both so not sure why the play store version isn’t working. 

I think when it asked me to install the APK I had to clear the cache so is it possible that’s related?

Thanks. 

Brian M. Bento

**Comment by andreahaku** [comment]
@brian-kryptomon is this happening on Android only? Can you please tell me on which device/os version? Thanks.

**Comment by brian-kryptomon** [comment]
It was on Android 12 / galaxy tab s8 - uninstalling and using the apk from github fixes the issue. The play store version doesn’t seem to work. 

Thanks. 

Brian M. Bento

**Comment by andreahaku** [comment]
@brian-kryptomon which version are you using that fixed the issue? Thanks

**Comment by mfahadasghar** [comment]
You can try this. Open Web3Wallet.cs and then in Start() and add this in start

```
#if UNITY_EDITOR
        Web3Wallet.url = "https://chainsafe.github.io/game-web3wallet/";
#else
        Web3Wallet.url = "https://metamask.app.link/dapp/chainsafe.github.io/game-web3wallet/";
#endif
```

This worked for me
