### ISSUE TITLE
WalletConnect RPC methods not working with the new version 4.2.2

### ISSUE THREAD

**Issue by mendelordanza** [MetaMask/metamask-mobile#3959]
**Describe the bug**
Seems like WalletConnect method calls is not being recognized by the new version 4.2.2 but works with version 4.0.1. Is this a bug on Metamask's end?

**To Reproduce**
_Steps to reproduce the behavior_
1. Use any method with WalletConnect
2. Redirect to the metamask mobile app
3. No transaction confirmation pop up showing

**Expected behavior**
Metamask should show the transaction confirmation pop up

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy S10e]
 - OS: [e.g. Android 12]
 - App Version [e.g. 4.2.2] - find version number in app from Settings > About MetaMask

**Comment by andreahaku** [comment]
@mendelordanza did you try version 4.3.x? This should fix this issue. Please report if it fixes. Thanks

**Comment by mendelordanza** [comment]
Hi @andreahaku . I tried downloading version 4.3.1 but it still doesn't recognize the method calls. I'm expecting to have some kind of popup (image below) when I used SendTransaction with WalletConnect.

The screenshot below uses version 4.0.1

![Screenshot_20220329-183105_MetaMask.jpg](https://user-images.githubusercontent.com/47298049/160592829-faccf5ef-66cf-4594-9428-4f8533d4bce1.jpg)

**Comment by andreahaku** [comment]
hi @mendelordanza, I've been able to replicate it on Android 12 and working on it. Just to confirm, you are able to connect with WC isn't it?

**Comment by mendelordanza** [comment]
Yes. I was able to create a session with WC
