### ISSUE TITLE
[Bug] Inputting a nonce value messes up the nonce counter setting a totally different number

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6482]
**Describe the bug**
Whenever we are inputting a nonce value manually (instead of using the increase/decrease arrows) we can see how the value we set, it's not the value it is send. The transaction nonce counter seems completely broken after that.

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/54408225/9cc529ef-18bd-43bb-9ef1-971b5eb0c8c4

**To Reproduce**
_Steps to reproduce the behavior_
1. Enable Nonce Edit in Advanced Settings
2. Go to test-dapp
3. Click Send EIP1559
4. Click Nonce
5. Edit the nonce by inputting a number manually
6. See how your number is displayed correctly
7. Confirm the transaction
8. See the nonce value is another on in the transaction details
9. Click Send EIP1559 again
10. See how the nonce counter is displaying a totally wrong value - nonce counter seems messed up

**Expected behavior**
Nonce should be updated correctly.

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: `6.7` it was working on `6.6`

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by wachunei** [comment]
😬 0x260 is 608, it is being read as hex 😅

**Comment by hesterbruikman** [comment]
That implies that the nonce is set correctly, but the display is not. Because of this distinction I consider it a sev1, but not a release blocker.

**Comment by bschorchit** [comment]
@seaona question that came up from @hesterbruikman on slack: are you able to confirm the transaction with the wrong nonce?

**Comment by seaona** [comment]
The transaction is sent with the wrong nonce @bschorchit @hesterbruikman 

https://github.com/MetaMask/metamask-mobile/assets/54408225/5074cb46-17ca-467b-81fd-00001b8d98e9

**Comment by hesterbruikman** [comment]
Few thoughts on this issue:

- It seems related to BigInt patch. @Cal-L can you confirm whether the BigInt patch could cause nonce to show as hex value?
- If this is a result of the BigInt patch, the issue should be resolved once the patch is removed after RN upgrade is completed. @seaona I think you should be able to confirm with a QA build (build is WIP this week)
- We might want to include a validation of the nonce. Any none other than the `last used` and `last used +1` should be flagged as invalid. That wouldn't solve this issue as the user would still provide the correct nonce in the UI
- Given that etherscan doesn't recognise the tx hash, I wonder if the transaction is actually submitted. It seems Infura returns a tx hash which only happens if the transaction is submitted, but it's odd that Etherscan doesn't recognize this. @bschorchit who do you think can provide clarity on this? Would this be on the API side or the controller?

Lastly, I propose to move this down to sev2.

**Comment by hesterbruikman** [comment]
@seaona I'm trying to reproduce the issue. Could you please point me to a build that you're finding this issue? I installed a cut of 7.1.0 of May 31st and can't reproduce the issue on that build.

**Comment by Jonathansoufer** [comment]
I think the problem happens due a `BNToHex(nonce);` happening on:

File: `app/components/Views/SendFlow/Confirm/index.js` 
Line: 617
Code: `if (showCustomNonce && nonce) transaction.nonce = BNToHex(nonce);`

**and**

File: `app/components/Views/Approval/index.js` 
Line: 338
Code: `if (showCustomNonce && nonce) transactionToSend.nonce = BNToHex(nonce);`

**Based on the docs**, transaction nonce is a **number**, so this conversion could be wrongly taking place and causing the problem.

Action Plan: Converting the nonce to number since its using the any type on this codebase, and passing it to transaction payload.

**Comment by tommasini** [comment]
I believe this was fixed on 7.2.0 with this [PR](https://github.com/MetaMask/metamask-mobile/pull/6712) 
https://recordit.co/1AAWQD0GYK
I can't reproduce it, @seaona are you still able to reproduce it?

**Comment by seaona** [comment]
The issue is still reproduceable in production cc @hesterbruikman 

- Pixel 6
- Android
- `7.8.0 (1174)`

https://github.com/MetaMask/metamask-mobile/assets/54408225/c9eb3674-714c-4f0c-8a4e-f1c8ea05e5a6

**Comment by hesterbruikman** [comment]
@seaona This was a great catch and I missed the follow-up. Seems like you caught our recent nonce issue ahead of time. Would you say this is the same? I'm not totally sure because the first report is on 6.7 and it only reached production in 7.8.0

**Comment by bschorchit** [comment]
Scope of this issue should only focus on the conversion issue from hex to decimal value

**Comment by bschorchit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-mobile/6482?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun

**Comment by bschorchit** [comment]
We should follow what extension does for input validation
