### ISSUE TITLE
[WalletConnect] RN upgrade issues - WC V1&V2

### ISSUE THREAD

**Issue by christopherferreira9** [MetaMask/metamask-mobile#6583]
ReactNative ugrade WalletConnect issues.

On android: 
- V2 deeplinks but doesn't show the connect modal
- v2 QR Code doesn't show the connect modal

On iOS:
- v1 & v2 deeplinks makes the wallet crash 

**Screenshots**
Crash:
https://images.zenhubusercontent.com/141427485/c6f1e77d-7cc2-4938-9489-c44bf91375ae/screen_recording_2023_06_09_at_18_51_54.mov

Unresponsive:
https://images.zenhubusercontent.com/141427485/c6f25b9d-7db6-405e-8bb7-88afc160650d/screen_recording_2023_06_09_at_18_53_17.mov

**To Reproduce**
- Open the [WalletConnect Dapp](https://feba4b8b.web3modal-dev.pages.dev/v2Customised) on the mobile browser
- Tap Connect
- See Error

- Open the [WalletConnect Dapp](https://feba4b8b.web3modal-dev.pages.dev/v2Customised) on the desktop browser
- Tap Connect
- Scan the QR Code
- See Error

**Expected behavior**
- You're able to connect
- Wallet sends you back to Dapp

**Comment by Z-Hayk** [comment]
@christopherferreira9 Hello.

You use WalletConnect V2?

**Comment by jpcloureiro** [comment]
Together with @tommasini we implemented this feature natively to replace `react-native-minimizer` dependency

fixed by [fd84cc5](https://github.com/MetaMask/metamask-mobile/pull/6220/commits/fd84cc56c2d0ff78ec2d668b6b74db06134ef338) & [c13b69f](https://github.com/MetaMask/metamask-mobile/pull/6220/commits/c13b69fbb4fc7322cb685c3114e830124951917e)

**Comment by christopherferreira9** [comment]
Retested on commit d43ee8c0b14a5e9e671b82d7d3f17ee57bb4073b from ```/upgrade/react-native/0.71.6-hermes```
On android:
- V2 deeplinks but doesn't show the connect modal -> Still happening 
- v2 QR Code doesn't show the connect modal -> Still happening 

On iOS:
v1 & v2 deeplinks makes the wallet crash -> All issues solved

**Comment by jpcloureiro** [comment]
Hey @christopherferreira9 
Thanks for the feedback.

I've pushed [this commit](https://github.com/MetaMask/metamask-mobile/pull/6220/commits/609fc932aed50211b27fbe42906380990f6b8460) that fixes WC V2 on Android.

We should be able now to get the modals.

**Comment by christopherferreira9** [comment]
@jpcloureiro it seems to be fixed. Both V1 and V2 work on android and iOS 🎉
