### ISSUE TITLE
signMessage throws "code": 1, "message": "Invalid Id" error sometimes

### ISSUE THREAD

**Issue by mqklin** [MetaMask/metamask-mobile#6735]
**Describe the bug**
signMessage throws "code": 1, "message": "Invalid Id" error sometimes. But sometimes it gets called properly (Sign a message modal appears in the iOS MM app).

**Screenshots**
![image](https://github.com/MetaMask/metamask-mobile/assets/9456433/0bcc4beb-20ed-4401-bbc9-9eddf2ddbb66)

**To Reproduce**
_Steps to reproduce the behavior_
1. Call signMessage several times (I use ethers.js v6), and soon or later you'll see the error.

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
- Device: iPhone 12 mini
- OS: iOS 16.5.1
- App Version: 7.0.1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by Shitikyan** [comment]
I also have such a case but only on specific iPhones in Specific regions. 
My guess is that the issue is timing related  and happens in cases where a  request (personal_sign in my case)
is made right after a session is established but Metamask hasn't yet committed the session. 


The sequence of events that could cause this: 

Dapp: Sends a session propsosal
Metamask: Shows the approval dialog (https://github.com/MetaMask/metamask-mobile/blob/151b54e0303d1b0131f21ec8297b857f9cfae7f5/app/core/WalletConnect/WalletConnectV2.ts#L519)
Metamask: Responds back with session approval (https://github.com/MetaMask/metamask-mobile/blob/151b54e0303d1b0131f21ec8297b857f9cfae7f5/app/core/WalletConnect/WalletConnectV2.ts#L556)
Dapp: Receives session approval 
Dapp: Sends a personal_sign request over the established session 
Metamask: Rejects the request since it hasn't saved the session in its in-memory dictionary. (https://github.com/MetaMask/metamask-mobile/blob/151b54e0303d1b0131f21ec8297b857f9cfae7f5/app/core/WalletConnect/WalletConnectV2.ts#L589)
Metamask: Belatedly saves the session in its in-memory dictionary. (https://github.com/MetaMask/metamask-mobile/blob/151b54e0303d1b0131f21ec8297b857f9cfae7f5/app/core/WalletConnect/WalletConnectV2.ts#L571)

**Comment by anaamolnar** [comment]
Hey @mqklin. Thanks for your report! Could you please check if you are experiencing the same issue with the latest version available in the App Store? Thank you!

**Comment by mqklin** [comment]
hey @anaamolnar 
No, I can't confirm, as I get now this error for every trying to sign a message. Or I get infinite spinner and can't even see a MetaMask interface (pinged you in other task)

**Comment by gritaliana** [comment]
This is an issue also with web dApp. 
And I am not so sure this has smth to do with devices itself.

Created UI for connecting with wallet, working on macOS 13.4.1 (c), Chrome. 
Connecting with metamask Wallet from IPhone X, iOS 16.5.1.

Used packages:
 "@walletconnect/modal": "^2.6.1",
 "@walletconnect/sign-client": "^2.9.2",
 
After session is received, if I am trying to immediately call 'personal_sign', or 'eth_sendTransaction' - it will fall with "Invalid id" error. 
**IF wrap those API calls in setTimeout** with **1000** milliseconds delay - everything works fine. 

So, I assume it is an issue inside Metamask. 

P.S. Trust wallet works perfectly fine without ant timeouts.

**Comment by mqklin** [comment]
Closing the issue, seems like it's fixed in some newest version.

**Comment by belbix** [comment]
The issue still happening and it is silently ignored with just `console.error`
I recommend at least adding DevLogger in the catch section
https://github.com/MetaMask/metamask-mobile/blob/main/app/core/WalletConnect/WalletConnectV2.ts#L817-L850

I have zero clue what happening but `Invalid Id` error exists for some my users.

**Comment by belbix** [comment]
In my case helped properly fill `metadata` section in `EthereumProviderOptions`
