### ISSUE TITLE
Vault Corruption Flow: Users who already imported their wallet are prompted with the "Protect your wallet modal" 

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#6991]
**Describe the bug**
If a user goes through the vault corruption flow while having an imported wallet, they are prompted with the `Protect your wallet modal` even though they already imported their wallet. The protect your wallet modal should only appear for new wallets not imported wallets. 

**Screenshots**
See recording [here](http://recordit.co/9iyOsOkDLV) compared to new wallet users [who are not prompted](http://recordit.co/XxBWH2kOmE) with the `Protect your wallet modal`. 

**To Reproduce**
Install v6.6 (1114)
Import your wallet
Update the app to 7.1 (1125)
Notice the vault corruption flow is triggered.
Kill the app
install v7.4.1 (1161) This is the build with the fix.
After entering your password and going through the vault corruption flow, The protect your wallet modal is triggered. 

**Expected behavior**
The `Protect your wallet modal` should not be displayed with users who imported their wallet. 

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by sethkfman** [comment]
@cortisiko I think this bug is resolved. Can you confirm and close?

**Comment by cortisiko** [comment]
@sethkfman This is still not resolved. We decided the issue reported above is not a blocker for the original vault corruption fix: https://github.com/MetaMask/metamask-mobile/pull/6957  

See slack thread here: https://consensys.slack.com/archives/C05HRMJU9R7/p1692120674274269?thread_ts=1692109563.239589&cid=C05HRMJU9R7

**Comment by plasmacorral** [comment]
Just experienced this on v7.5.0 build 1167, Android 13.
