### ISSUE TITLE
Settings > General causes unexpected behavior

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-mobile#945]
Couple different reports:
- When I try to go to General in settings it loads it for a split second then goes back to the previous screen.
- When clicking on general in settings, it quickly goes away and then takes me to Browser.
- after clicking general in settings, the app crashes

Reported on both iOS and Android

**Comment by estebanmino** [comment]
hopefully fixed with https://github.com/MetaMask/metamask-mobile/pull/922 we'll track this issue

**Comment by brunobar79** [comment]
Closing this one and reopening if we heard reports on it after v0.2+

**Comment by ayobuenavista** [comment]
I am still experiencing this bug with v0.2.3 (16). It is always reproducibile when I open the General settings.

Android 9 (with latest updates)
Pixel 3 XL

**Comment by ayobuenavista** [comment]
> Hey @ayobuenavista I just tried on my Google Pixel 3 XL as well, but couldn't reproduce, am I doing something differently?
> 
> Seen here = https://recordit.co/zunaoTvOQU

I've recorded this directly from my Pixel 3 XL. [https://www.youtube.com/watch?v=Zc5Fvke5SRo](https://www.youtube.com/watch?v=Zc5Fvke5SRo)

I haven't done anything out of the ordinary other than installing the app and doing the above in the video.
